//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blish_HUD.Strings.GameServices.Contexts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Festivals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Festivals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blish_HUD.Strings.GameServices.Contexts.Festivals", typeof(Festivals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon Bash.
        /// </summary>
        internal static string Festival_DragonBash {
            get {
                return ResourceManager.GetString("Festival_DragonBash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festival of the Four Winds.
        /// </summary>
        internal static string Festival_FestivalOfTheFourWinds {
            get {
                return ResourceManager.GetString("Festival_FestivalOfTheFourWinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halloween.
        /// </summary>
        internal static string Festival_Halloween {
            get {
                return ResourceManager.GetString("Festival_Halloween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunar New Year.
        /// </summary>
        internal static string Festival_LunarNewYear {
            get {
                return ResourceManager.GetString("Festival_LunarNewYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Adventure Festival.
        /// </summary>
        internal static string Festival_SuperAdventureFestival {
            get {
                return ResourceManager.GetString("Festival_SuperAdventureFestival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wintersday.
        /// </summary>
        internal static string Festival_Wintersday {
            get {
                return ResourceManager.GetString("Festival_Wintersday", resourceCulture);
            }
        }
    }
}
