//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blish_HUD.Strings.GameServices {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GraphicsService___Copier {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GraphicsService___Copier() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blish_HUD.Strings.GameServices.GraphicsService - Copier", typeof(GraphicsService___Copier).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Graphics Settings.
        /// </summary>
        internal static string GraphicsSettingsSection {
            get {
                return ResourceManager.GetString("GraphicsSettingsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enables additional scaling of the UI according to your system settings..
        /// </summary>
        internal static string Setting_DPIScaling_Description {
            get {
                return ResourceManager.GetString("Setting_DPIScaling_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DPI Scaling.
        /// </summary>
        internal static string Setting_DPIScaling_DisplayName {
            get {
                return ResourceManager.GetString("Setting_DPIScaling_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The method used to determine the framerate that Blish HUD should run at..
        /// </summary>
        internal static string Setting_FramerateLimiter_Description {
            get {
                return ResourceManager.GetString("Setting_FramerateLimiter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Frame Limiter.
        /// </summary>
        internal static string Setting_FramerateLimiter_DisplayName {
            get {
                return ResourceManager.GetString("Setting_FramerateLimiter_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (Disabled because Blish HUD was started with --maxfps specified).
        /// </summary>
        internal static string Setting_FramerateLimiter_Locked_Description {
            get {
                return ResourceManager.GetString("Setting_FramerateLimiter_Locked_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If enabled, the character position is smoothed to prevent 3D overlay elements from jumping around..
        /// </summary>
        internal static string Setting_SmoothCharacterPosition_Description {
            get {
                return ResourceManager.GetString("Setting_SmoothCharacterPosition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Smooth Character Position.
        /// </summary>
        internal static string Setting_SmoothCharacterPosition_DisplayName {
            get {
                return ResourceManager.GetString("Setting_SmoothCharacterPosition_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Determines the scaling of the UI. Either sync with game or set manually.
        ///NOTE: &apos;Automatic&apos; will only update while logged in with a character.
        /// </summary>
        internal static string Setting_UIScaling_Description {
            get {
                return ResourceManager.GetString("Setting_UIScaling_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interface Size.
        /// </summary>
        internal static string Setting_UIScaling_DisplayName {
            get {
                return ResourceManager.GetString("Setting_UIScaling_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabling Vsync limits the frame rate of Blish HUD to the monitor refresh rate to prevent screen tearing..
        /// </summary>
        internal static string Setting_Vsync_Description {
            get {
                return ResourceManager.GetString("Setting_Vsync_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable Vsync.
        /// </summary>
        internal static string Setting_Vsync_DisplayName {
            get {
                return ResourceManager.GetString("Setting_Vsync_DisplayName", resourceCulture);
            }
        }
    }
}
