//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blish_HUD.Strings.GameServices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Gw2ApiService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Gw2ApiService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blish_HUD.Strings.GameServices.Gw2ApiService", typeof(Gw2ApiService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account display name, ID, home world, and list of guilds..
        /// </summary>
        internal static string TokenPermissionDescription_Account {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your currently equipped specializations, traits, skills, and equipment for all game modes..
        /// </summary>
        internal static string TokenPermissionDescription_Builds {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Builds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic information about your characters..
        /// </summary>
        internal static string TokenPermissionDescription_Characters {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guilds&apos; rosters, history, and MOTDs for all guilds you are a member of..
        /// </summary>
        internal static string TokenPermissionDescription_Guilds {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Guilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account bank, material storage, recipe unlocks, and character inventories..
        /// </summary>
        internal static string TokenPermissionDescription_Inventories {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Inventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your achievements, dungeon unlock status, mastery point assignments, and general PvE progress..
        /// </summary>
        internal static string TokenPermissionDescription_Progression {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Progression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your PvP stats, match history, reward track progression, and custom arena details..
        /// </summary>
        internal static string TokenPermissionDescription_Pvp {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Pvp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Trading Post transactions..
        /// </summary>
        internal static string TokenPermissionDescription_Tradingpost {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Tradingpost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your wardrobe unlocks—skins, dyes, minipets, finishers, etc.—and currently equipped skins..
        /// </summary>
        internal static string TokenPermissionDescription_Unlocks {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Unlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account&apos;s wallet..
        /// </summary>
        internal static string TokenPermissionDescription_Wallet {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Wallet", resourceCulture);
            }
        }
    }
}
