//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blish_HUD.Strings.GameServices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Gw2ApiService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Gw2ApiService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blish_HUD.Strings.GameServices.Gw2ApiService", typeof(Gw2ApiService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        internal static string AccountInfo_Character {
            get {
                return ResourceManager.GetString("AccountInfo_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commander.
        /// </summary>
        internal static string AccountInfo_Commander {
            get {
                return ResourceManager.GetString("AccountInfo_Commander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to the official applications page..
        /// </summary>
        internal static string CreateTokenInstructions_Step1 {
            get {
                return ResourceManager.GetString("CreateTokenInstructions_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;New Key&quot;..
        /// </summary>
        internal static string CreateTokenInstructions_Step2 {
            get {
                return ResourceManager.GetString("CreateTokenInstructions_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all permissions and press the
        ///&quot;CREATE API KEY&quot; button..
        /// </summary>
        internal static string CreateTokenInstructions_Step3 {
            get {
                return ResourceManager.GetString("CreateTokenInstructions_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the new key..
        /// </summary>
        internal static string CreateTokenInstructions_Step4 {
            get {
                return ResourceManager.GetString("CreateTokenInstructions_Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste the key into the field above and
        ///press &quot;Register&quot;..
        /// </summary>
        internal static string CreateTokenInstructions_Step5 {
            get {
                return ResourceManager.GetString("CreateTokenInstructions_Step5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can register a key without all permissions, but some
        ///features and modules may fail to function properly.
        ///
        ///At a minimum, &quot;Account&quot; and &quot;Character&quot; permissions
        ///are required..
        /// </summary>
        internal static string CreateTokenInstructions_Warning {
            get {
                return ResourceManager.GetString("CreateTokenInstructions_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Applications.
        /// </summary>
        internal static string Link_ManageApplications {
            get {
                return ResourceManager.GetString("Link_ManageApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Token.
        /// </summary>
        internal static string ManageApiKeys_DeleteToken {
            get {
                return ResourceManager.GetString("ManageApiKeys_DeleteToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string ManageApiKeys_Register {
            get {
                return ResourceManager.GetString("ManageApiKeys_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register API Key.
        /// </summary>
        internal static string ManageApiKeys_Title {
            get {
                return ResourceManager.GetString("ManageApiKeys_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage API Keys.
        /// </summary>
        internal static string ManageApiKeysSection {
            get {
                return ResourceManager.GetString("ManageApiKeysSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no name).
        /// </summary>
        internal static string Token_NoName {
            get {
                return ResourceManager.GetString("Token_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account display name, ID, home world, and list of guilds..
        /// </summary>
        internal static string TokenPermissionDescription_Account {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your currently equipped specializations, traits, skills, and equipment for all game modes..
        /// </summary>
        internal static string TokenPermissionDescription_Builds {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Builds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic information about your characters..
        /// </summary>
        internal static string TokenPermissionDescription_Characters {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guilds&apos; rosters, history, and MOTDs for all guilds you are a member of..
        /// </summary>
        internal static string TokenPermissionDescription_Guilds {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Guilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account bank, material storage, recipe unlocks, and character inventories..
        /// </summary>
        internal static string TokenPermissionDescription_Inventories {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Inventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your achievements, dungeon unlock status, mastery point assignments, and general PvE progress..
        /// </summary>
        internal static string TokenPermissionDescription_Progression {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Progression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your PvP stats, match history, reward track progression, and custom arena details..
        /// </summary>
        internal static string TokenPermissionDescription_Pvp {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Pvp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Trading Post transactions..
        /// </summary>
        internal static string TokenPermissionDescription_Tradingpost {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Tradingpost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your wardrobe unlocks—skins, dyes, minipets, finishers, etc.—and currently equipped skins..
        /// </summary>
        internal static string TokenPermissionDescription_Unlocks {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Unlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account&apos;s wallet..
        /// </summary>
        internal static string TokenPermissionDescription_Wallet {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting account details failed.
        /// </summary>
        internal static string TokenStatus_AccountFailed {
            get {
                return ResourceManager.GetString("TokenStatus_AccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load token..
        /// </summary>
        internal static string TokenStatus_FailedToLoad {
            get {
                return ResourceManager.GetString("TokenStatus_FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        internal static string TokenStatus_InvalidToken {
            get {
                return ResourceManager.GetString("TokenStatus_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required permissions.
        /// </summary>
        internal static string TokenStatus_MissingMinPermission {
            get {
                return ResourceManager.GetString("TokenStatus_MissingMinPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token missing permissions.
        /// </summary>
        internal static string TokenStatus_PartialPermission {
            get {
                return ResourceManager.GetString("TokenStatus_PartialPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}) - Valid token.
        /// </summary>
        internal static string TokenStatus_ValidToken {
            get {
                return ResourceManager.GetString("TokenStatus_ValidToken", resourceCulture);
            }
        }
    }
}
