//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blish_HUD.Strings.GameServices {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModulesService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModulesService() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blish_HUD.Strings.GameServices.ModulesService", typeof(ModulesService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Missing required permissions:.
        /// </summary>
        internal static string ApiPermission_MissingRequiredPermissions {
            get {
                return ResourceManager.GetString("ApiPermission_MissingRequiredPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No permissions requested.
        /// </summary>
        internal static string ApiPermission_NoPermissionsRequested {
            get {
                return ResourceManager.GetString("ApiPermission_NoPermissionsRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Optional.
        /// </summary>
        internal static string ApiPermission_Optional {
            get {
                return ResourceManager.GetString("ApiPermission_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à has requested to read from the following APIs.
        /// </summary>
        internal static string ApiPermission_RequestedApiPermissionsInfo {
            get {
                return ResourceManager.GetString("ApiPermission_RequestedApiPermissionsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Required.
        /// </summary>
        internal static string ApiPermission_Required {
            get {
                return ResourceManager.GetString("ApiPermission_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This module relies on dependencies not currently available:.
        /// </summary>
        internal static string Dependency_MissingDependencies {
            get {
                return ResourceManager.GetString("Dependency_MissingDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No dependencies.
        /// </summary>
        internal static string Dependency_NoDependencies {
            get {
                return ResourceManager.GetString("Dependency_NoDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [Not Enabled].
        /// </summary>
        internal static string Dependency_NotEnabled {
            get {
                return ResourceManager.GetString("Dependency_NotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [Not Found].
        /// </summary>
        internal static string Dependency_NotFound {
            get {
                return ResourceManager.GetString("Dependency_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Requires {0}.
        /// </summary>
        internal static string Dependency_RequiresVersion {
            get {
                return ResourceManager.GetString("Dependency_RequiresVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [Wrong Version].
        /// </summary>
        internal static string Dependency_WrongVersion {
            get {
                return ResourceManager.GetString("Dependency_WrongVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage Modules.
        /// </summary>
        internal static string ManageModulesSection {
            get {
                return ResourceManager.GetString("ManageModulesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à API Permissions.
        /// </summary>
        internal static string ModuleManagement_ApiPermissions {
            get {
                return ResourceManager.GetString("ModuleManagement_ApiPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authored by.
        /// </summary>
        internal static string ModuleManagement_AuthoredBy {
            get {
                return ResourceManager.GetString("ModuleManagement_AuthoredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear Permissions.
        /// </summary>
        internal static string ModuleManagement_ClearPermissions {
            get {
                return ResourceManager.GetString("ModuleManagement_ClearPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dependencies.
        /// </summary>
        internal static string ModuleManagement_Dependencies {
            get {
                return ResourceManager.GetString("ModuleManagement_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        internal static string ModuleManagement_Description {
            get {
                return ResourceManager.GetString("ModuleManagement_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable Module.
        /// </summary>
        internal static string ModuleManagement_DisableModule {
            get {
                return ResourceManager.GetString("ModuleManagement_DisableModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable Module.
        /// </summary>
        internal static string ModuleManagement_EnableModule {
            get {
                return ResourceManager.GetString("ModuleManagement_EnableModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ignore Dependency Requirements.
        /// </summary>
        internal static string ModuleManagement_IgnoreDependencyRequirements {
            get {
                return ResourceManager.GetString("ModuleManagement_IgnoreDependencyRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify Permissions.
        /// </summary>
        internal static string ModuleManagement_ModifyPermissions {
            get {
                return ResourceManager.GetString("ModuleManagement_ModifyPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Module Settings.
        /// </summary>
        internal static string ModuleManagement_ModuleSettings {
            get {
                return ResourceManager.GetString("ModuleManagement_ModuleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View Module Logs.
        /// </summary>
        internal static string ModuleManagement_ViewModuleLogs {
            get {
                return ResourceManager.GetString("ModuleManagement_ViewModuleLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear Settings.
        /// </summary>
        internal static string ModuleOption_ClearSettings {
            get {
                return ResourceManager.GetString("ModuleOption_ClearSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can&apos;t clear settings while the module is enabled..
        /// </summary>
        internal static string ModuleOption_ClearSettings_DescriptionDisabled {
            get {
                return ResourceManager.GetString("ModuleOption_ClearSettings_DescriptionDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset the module settings back to their default..
        /// </summary>
        internal static string ModuleOption_ClearSettings_DescriptionEnabled {
            get {
                return ResourceManager.GetString("ModuleOption_ClearSettings_DescriptionEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Module.
        /// </summary>
        internal static string ModuleOption_DeleteModule {
            get {
                return ResourceManager.GetString("ModuleOption_DeleteModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open &apos;{0}&apos; Directory.
        /// </summary>
        internal static string ModuleOption_OpenDir {
            get {
                return ResourceManager.GetString("ModuleOption_OpenDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings will show when Module is enabled.
        /// </summary>
        internal static string ModuleSettings_ShownWhenEnabled {
            get {
                return ResourceManager.GetString("ModuleSettings_ShownWhenEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Module Version Is Too Old.
        /// </summary>
        internal static string ModuleState_Custom_ExplicitlyIncompatible {
            get {
                return ResourceManager.GetString("ModuleState_Custom_ExplicitlyIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disabled.
        /// </summary>
        internal static string ModuleState_Disabled {
            get {
                return ResourceManager.GetString("ModuleState_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disabling.
        /// </summary>
        internal static string ModuleState_Disabling {
            get {
                return ResourceManager.GetString("ModuleState_Disabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabled.
        /// </summary>
        internal static string ModuleState_Enabled {
            get {
                return ResourceManager.GetString("ModuleState_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fatal Error.
        /// </summary>
        internal static string ModuleState_FatalError {
            get {
                return ResourceManager.GetString("ModuleState_FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading.
        /// </summary>
        internal static string ModuleState_Loading {
            get {
                return ResourceManager.GetString("ModuleState_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You don&apos;t currently have any modules.
        ///Download some modules and place them in the modules folder..
        /// </summary>
        internal static string NoModules_Info {
            get {
                return ResourceManager.GetString("NoModules_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Modules Folder.
        /// </summary>
        internal static string NoModules_OpenFolder {
            get {
                return ResourceManager.GetString("NoModules_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Installing....
        /// </summary>
        internal static string PkgInstall_Progress_Installing {
            get {
                return ResourceManager.GetString("PkgInstall_Progress_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Upgrading....
        /// </summary>
        internal static string PkgInstall_Progress_Upgrading {
            get {
                return ResourceManager.GetString("PkgInstall_Progress_Upgrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current Version.
        /// </summary>
        internal static string PkgManagement_CurrentVersion {
            get {
                return ResourceManager.GetString("PkgManagement_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Downgrade.
        /// </summary>
        internal static string PkgManagement_Downgrade {
            get {
                return ResourceManager.GetString("PkgManagement_Downgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Install.
        /// </summary>
        internal static string PkgManagement_Install {
            get {
                return ResourceManager.GetString("PkgManagement_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blish HUD requires a restart before some modules can be re-enabled..
        /// </summary>
        internal static string PkgManagement_ModulesNeedRestart {
            get {
                return ResourceManager.GetString("PkgManagement_ModulesNeedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checking repository....
        /// </summary>
        internal static string PkgManagement_Progress_CheckingRepository {
            get {
                return ResourceManager.GetString("PkgManagement_Progress_CheckingRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to pull root from package repo..
        /// </summary>
        internal static string PkgManagement_Progress_FailedToGetReleases {
            get {
                return ResourceManager.GetString("PkgManagement_Progress_FailedToGetReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to get or parse latest repo manifest..
        /// </summary>
        internal static string PkgManagement_Progress_FailedToReadOrParseRepoManifest {
            get {
                return ResourceManager.GetString("PkgManagement_Progress_FailedToReadOrParseRepoManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Getting module list....
        /// </summary>
        internal static string PkgManagement_Progress_GettingModuleList {
            get {
                return ResourceManager.GetString("PkgManagement_Progress_GettingModuleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update.
        /// </summary>
        internal static string PkgManagement_Update {
            get {
                return ResourceManager.GetString("PkgManagement_Update", resourceCulture);
            }
        }
    }
}
