//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blish_HUD.Strings.GameServices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModulesService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModulesService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blish_HUD.Strings.GameServices.ModulesService", typeof(ModulesService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required permissions:.
        /// </summary>
        internal static string ApiPermission_MissingRequiredPermissions {
            get {
                return ResourceManager.GetString("ApiPermission_MissingRequiredPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permissions requested.
        /// </summary>
        internal static string ApiPermission_NoPermissionsRequested {
            get {
                return ResourceManager.GetString("ApiPermission_NoPermissionsRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        internal static string ApiPermission_Optional {
            get {
                return ResourceManager.GetString("ApiPermission_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has requested to read from the following APIs.
        /// </summary>
        internal static string ApiPermission_RequestedApiPermissionsInfo {
            get {
                return ResourceManager.GetString("ApiPermission_RequestedApiPermissionsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string ApiPermission_Required {
            get {
                return ResourceManager.GetString("ApiPermission_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This module relies on dependencies not currently available:.
        /// </summary>
        internal static string Dependency_MissingDependencies {
            get {
                return ResourceManager.GetString("Dependency_MissingDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dependencies.
        /// </summary>
        internal static string Dependency_NoDependencies {
            get {
                return ResourceManager.GetString("Dependency_NoDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Not Enabled].
        /// </summary>
        internal static string Dependency_NotEnabled {
            get {
                return ResourceManager.GetString("Dependency_NotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Not Found].
        /// </summary>
        internal static string Dependency_NotFound {
            get {
                return ResourceManager.GetString("Dependency_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires {0}.
        /// </summary>
        internal static string Dependency_RequiresVersion {
            get {
                return ResourceManager.GetString("Dependency_RequiresVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Wrong Version].
        /// </summary>
        internal static string Dependency_WrongVersion {
            get {
                return ResourceManager.GetString("Dependency_WrongVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Modules.
        /// </summary>
        internal static string ManageModulesSection {
            get {
                return ResourceManager.GetString("ManageModulesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Permissions.
        /// </summary>
        internal static string ModuleManagement_ApiPermissions {
            get {
                return ResourceManager.GetString("ModuleManagement_ApiPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authored by.
        /// </summary>
        internal static string ModuleManagement_AuthoredBy {
            get {
                return ResourceManager.GetString("ModuleManagement_AuthoredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Permissions.
        /// </summary>
        internal static string ModuleManagement_ClearPermissions {
            get {
                return ResourceManager.GetString("ModuleManagement_ClearPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        internal static string ModuleManagement_Dependencies {
            get {
                return ResourceManager.GetString("ModuleManagement_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ModuleManagement_Description {
            get {
                return ResourceManager.GetString("ModuleManagement_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Module.
        /// </summary>
        internal static string ModuleManagement_DisableModule {
            get {
                return ResourceManager.GetString("ModuleManagement_DisableModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Module.
        /// </summary>
        internal static string ModuleManagement_EnableModule {
            get {
                return ResourceManager.GetString("ModuleManagement_EnableModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Dependency Requirements.
        /// </summary>
        internal static string ModuleManagement_IgnoreDependencyRequirements {
            get {
                return ResourceManager.GetString("ModuleManagement_IgnoreDependencyRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Permissions.
        /// </summary>
        internal static string ModuleManagement_ModifyPermissions {
            get {
                return ResourceManager.GetString("ModuleManagement_ModifyPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Settings.
        /// </summary>
        internal static string ModuleManagement_ModuleSettings {
            get {
                return ResourceManager.GetString("ModuleManagement_ModuleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Module Logs.
        /// </summary>
        internal static string ModuleManagement_ViewModuleLogs {
            get {
                return ResourceManager.GetString("ModuleManagement_ViewModuleLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Settings.
        /// </summary>
        internal static string ModuleOption_ClearSettings {
            get {
                return ResourceManager.GetString("ModuleOption_ClearSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t clear settings while the module is enabled..
        /// </summary>
        internal static string ModuleOption_ClearSettings_DescriptionDisabled {
            get {
                return ResourceManager.GetString("ModuleOption_ClearSettings_DescriptionDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the module settings back to their default..
        /// </summary>
        internal static string ModuleOption_ClearSettings_DescriptionEnabled {
            get {
                return ResourceManager.GetString("ModuleOption_ClearSettings_DescriptionEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Module.
        /// </summary>
        internal static string ModuleOption_DeleteModule {
            get {
                return ResourceManager.GetString("ModuleOption_DeleteModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &apos;{0}&apos; Directory.
        /// </summary>
        internal static string ModuleOption_OpenDir {
            get {
                return ResourceManager.GetString("ModuleOption_OpenDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings will show when Module is enabled.
        /// </summary>
        internal static string ModuleSettings_ShownWhenEnabled {
            get {
                return ResourceManager.GetString("ModuleSettings_ShownWhenEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Version Is Incompatible.
        /// </summary>
        internal static string ModuleState_Custom_ExplicitlyIncompatible {
            get {
                return ResourceManager.GetString("ModuleState_Custom_ExplicitlyIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string ModuleState_Disabled {
            get {
                return ResourceManager.GetString("ModuleState_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling.
        /// </summary>
        internal static string ModuleState_Disabling {
            get {
                return ResourceManager.GetString("ModuleState_Disabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string ModuleState_Enabled {
            get {
                return ResourceManager.GetString("ModuleState_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        internal static string ModuleState_FatalError {
            get {
                return ResourceManager.GetString("ModuleState_FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string ModuleState_Loading {
            get {
                return ResourceManager.GetString("ModuleState_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t currently have any modules.
        ///Download some modules and place them in the modules folder..
        /// </summary>
        internal static string NoModules_Info {
            get {
                return ResourceManager.GetString("NoModules_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Modules Folder.
        /// </summary>
        internal static string NoModules_OpenFolder {
            get {
                return ResourceManager.GetString("NoModules_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        internal static string PkgInstall_Progress_Installing {
            get {
                return ResourceManager.GetString("PkgInstall_Progress_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading....
        /// </summary>
        internal static string PkgInstall_Progress_Upgrading {
            get {
                return ResourceManager.GetString("PkgInstall_Progress_Upgrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version.
        /// </summary>
        internal static string PkgManagement_CurrentVersion {
            get {
                return ResourceManager.GetString("PkgManagement_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downgrade.
        /// </summary>
        internal static string PkgManagement_Downgrade {
            get {
                return ResourceManager.GetString("PkgManagement_Downgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string PkgManagement_Install {
            get {
                return ResourceManager.GetString("PkgManagement_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Release.
        /// </summary>
        internal static string PkgManagement_IsPreview {
            get {
                return ResourceManager.GetString("PkgManagement_IsPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blish HUD requires a restart before some modules can be re-enabled..
        /// </summary>
        internal static string PkgManagement_ModulesNeedRestart {
            get {
                return ResourceManager.GetString("PkgManagement_ModulesNeedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        internal static string PkgManagement_MoreInfo {
            get {
                return ResourceManager.GetString("PkgManagement_MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking repository....
        /// </summary>
        internal static string PkgManagement_Progress_CheckingRepository {
            get {
                return ResourceManager.GetString("PkgManagement_Progress_CheckingRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to pull root from package repo..
        /// </summary>
        internal static string PkgManagement_Progress_FailedToGetReleases {
            get {
                return ResourceManager.GetString("PkgManagement_Progress_FailedToGetReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get or parse latest repo manifest..
        /// </summary>
        internal static string PkgManagement_Progress_FailedToReadOrParseRepoManifest {
            get {
                return ResourceManager.GetString("PkgManagement_Progress_FailedToReadOrParseRepoManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting module list....
        /// </summary>
        internal static string PkgManagement_Progress_GettingModuleList {
            get {
                return ResourceManager.GetString("PkgManagement_Progress_GettingModuleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string PkgManagement_Update {
            get {
                return ResourceManager.GetString("PkgManagement_Update", resourceCulture);
            }
        }
    }
}
