//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blish_HUD.Strings.GameServices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OverlayService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OverlayService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blish_HUD.Strings.GameServices.OverlayService", typeof(OverlayService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ©2010-{0} ArenaNet, LLC. All rights reserved. Guild Wars, Guild Wars 2, Heart of Thorns,
        ///Guild Wars 2: Path of Fire, ArenaNet, NCSOFT, the Interlocking NC Logo, and all associated
        ///logos and designs are trademarks or registered trademarks of NCSOFT Corporation. All other
        ///trademarks are the property of their respective owners..
        /// </summary>
        internal static string AboutAnetNotice {
            get {
                return ResourceManager.GetString("AboutAnetNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed and built with all the love in Tyria by
        ///the Blish HUD team with help from many more!.
        /// </summary>
        internal static string AboutLoveMessage {
            get {
                return ResourceManager.GetString("AboutLoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutSection {
            get {
                return ResourceManager.GetString("AboutSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeTab {
            get {
                return ResourceManager.GetString("HomeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Settings.
        /// </summary>
        internal static string OverlaySettingsSection {
            get {
                return ResourceManager.GetString("OverlaySettingsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the language used when displaying Blish HUD text and when requests are made to the GW2 web API..
        /// </summary>
        internal static string Setting_AppCulture_Description {
            get {
                return ResourceManager.GetString("Setting_AppCulture_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application &amp; API Language.
        /// </summary>
        internal static string Setting_AppCulture_DisplayName {
            get {
                return ResourceManager.GetString("Setting_AppCulture_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, Blish HUD will be shown in the taskbar while running..
        /// </summary>
        internal static string Setting_ShowInTaskbar_Description {
            get {
                return ResourceManager.GetString("Setting_ShowInTaskbar_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Taskbar.
        /// </summary>
        internal static string Setting_ShowInTaskbar_DisplayName {
            get {
                return ResourceManager.GetString("Setting_ShowInTaskbar_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true, Blish HUD will automatically minimize when GW2 closes and will continue running until GW2 is launched again.
        ///You can also use the Blish HUD icon in the tray to launch Guild Wars 2..
        /// </summary>
        internal static string Setting_StayInTray_Description {
            get {
                return ResourceManager.GetString("Setting_StayInTray_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray when Guild Wars 2 Closes..
        /// </summary>
        internal static string Setting_StayInTray_DisplayName {
            get {
                return ResourceManager.GetString("Setting_StayInTray_DisplayName", resourceCulture);
            }
        }
    }
}
