//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nspector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nspector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;CustomSettingNames&gt;
        ///  &lt;Settings&gt;
        ///    &lt;CustomSetting&gt;
        ///      &lt;UserfriendlyName&gt;SLI CFR Mode&lt;/UserfriendlyName&gt;
        ///      &lt;HexSettingID&gt;0x20343843&lt;/HexSettingID&gt;
        ///      &lt;GroupName&gt;6 - SLI&lt;/GroupName&gt;
        ///    &lt;/CustomSetting&gt;
        ///    &lt;!--&lt;CustomSetting&gt;
        ///      &lt;UserfriendlyName&gt;Enable Ansel&lt;/UserfriendlyName&gt;
        ///      &lt;HexSettingID&gt;0x1075D972&lt;/HexSettingID&gt;
        ///      &lt;GroupName&gt;5 - Common&lt;/GroupName&gt;
        ///      &lt;SettingValues&gt;
        ///        &lt;CustomSettingValue&gt;
        ///          &lt;UserfriendlyName&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CustomSettingNames {
            get {
                return ResourceManager.GetString("CustomSettingNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;CustomSettingNames&gt;
        ///  &lt;Settings&gt;
        ///    &lt;CustomSetting&gt;
        ///      &lt;UserfriendlyName&gt;Time&lt;/UserfriendlyName&gt;
        ///      &lt;HexSettingID&gt;0x70AD05C8&lt;/HexSettingID&gt;
        ///      &lt;GroupName&gt;7 - Stereo&lt;/GroupName&gt;
        ///      &lt;MinRequiredDriverVersion&gt;0&lt;/MinRequiredDriverVersion&gt;
        ///    &lt;/CustomSetting&gt;
        ///    &lt;CustomSetting&gt;
        ///      &lt;UserfriendlyName&gt;RunTimeName&lt;/UserfriendlyName&gt;
        ///      &lt;HexSettingID&gt;0x701A8BE4&lt;/HexSettingID&gt;
        ///      &lt;GroupName&gt;7 - Stereo&lt;/GroupName&gt;
        ///      &lt;MinRequiredDriverVersi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReferenceSettingNames {
            get {
                return ResourceManager.GetString("ReferenceSettingNames", resourceCulture);
            }
        }
    }
}
