// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: pipeline.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
[global::ProtoBuf.ProtoContract(Name = @"arc")]
public partial class Arc : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(2, Name = @"msgtype")]
    public Mtype Msgtype { get; set; }

    [global::ProtoBuf.ProtoMember(16, Name = @"greeting")]
    public bool Greeting
    {
        get { return __pbn__msg.Is(16) ? __pbn__msg.Boolean : default; }
        set { __pbn__msg = new global::ProtoBuf.DiscriminatedUnion32(16, value); }
    }
    public bool ShouldSerializeGreeting() => __pbn__msg.Is(16);
    public void ResetGreeting() => global::ProtoBuf.DiscriminatedUnion32.Reset(ref __pbn__msg, 16);

    private global::ProtoBuf.DiscriminatedUnion32 __pbn__msg;

    [global::ProtoBuf.ProtoMember(1, Name = @"imgui")]
    public bool Imgui
    {
        get { return __pbn__msg.Is(1) ? __pbn__msg.Boolean : default; }
        set { __pbn__msg = new global::ProtoBuf.DiscriminatedUnion32(1, value); }
    }
    public bool ShouldSerializeImgui() => __pbn__msg.Is(1);
    public void ResetImgui() => global::ProtoBuf.DiscriminatedUnion32.Reset(ref __pbn__msg, 1);

}

[global::ProtoBuf.ProtoContract(Name = @"mtype")]
public enum Mtype
{
    NoMsg = 0,
    Imgui = 1,
    Greeting = 2,
}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
