//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blish_HUD.Strings.GameServices.Modules {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RepoAndPkgManagement___Copier {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RepoAndPkgManagement___Copier() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blish_HUD.Strings.GameServices.Modules.RepoAndPkgManagement - Copier", typeof(RepoAndPkgManagement___Copier).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A newer version of this module is available..
        /// </summary>
        internal static string PkgRepo_PackageRelationship_CanUpdate {
            get {
                return ResourceManager.GetString("PkgRepo_PackageRelationship_CanUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This module is installed and up to date..
        /// </summary>
        internal static string PkgRepo_PackageRelationship_CurrentVersion {
            get {
                return ResourceManager.GetString("PkgRepo_PackageRelationship_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disabling module....
        /// </summary>
        internal static string PkgRepo_PackageStatus_DisablingModule {
            get {
                return ResourceManager.GetString("PkgRepo_PackageStatus_DisablingModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Only Show Installed Modules.
        /// </summary>
        internal static string PkgRepo_ProviderExtraOption_FilterInstalledModules {
            get {
                return ResourceManager.GetString("PkgRepo_ProviderExtraOption_FilterInstalledModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Only Show Modules With Updates.
        /// </summary>
        internal static string PkgRepo_ProviderExtraOption_FilterModulesWithUpdates {
            get {
                return ResourceManager.GetString("PkgRepo_ProviderExtraOption_FilterModulesWithUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Only Show Modules Not Installed.
        /// </summary>
        internal static string PkgRepo_ProviderExtraOption_FilterNotInstalledModules {
            get {
                return ResourceManager.GetString("PkgRepo_ProviderExtraOption_FilterNotInstalledModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Only Show Supported Versions.
        /// </summary>
        internal static string PkgRepo_ProviderExtraOption_FilterSupportedVersions {
            get {
                return ResourceManager.GetString("PkgRepo_ProviderExtraOption_FilterSupportedVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Force Reload Repository.
        /// </summary>
        internal static string PkgRepo_ProviderExtraOption_ReloadRepository {
            get {
                return ResourceManager.GetString("PkgRepo_ProviderExtraOption_ReloadRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Module Repo.
        /// </summary>
        internal static string PkgRepoSection {
            get {
                return ResourceManager.GetString("PkgRepoSection", resourceCulture);
            }
        }
    }
}
