//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blish_HUD.Strings.GameServices.Debug {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContingencyMessages___Copier {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContingencyMessages___Copier() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blish_HUD.Strings.GameServices.Debug.ContingencyMessages - Copier", typeof(ContingencyMessages___Copier).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is a custom &apos;d3dll.dll&apos; (e.g. ArcDPS) in the same directory as Blish HUD which will attempt to inject into Blish HUD and cause it to crash.  Please move Blish HUD to a different folder..
        /// </summary>
        internal static string ArcDpsSameDir_Description {
            get {
                return ResourceManager.GetString("ArcDpsSameDir_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blish HUD Can&apos;t Run!.
        /// </summary>
        internal static string ArcDpsSameDir_Title {
            get {
                return ResourceManager.GetString("ArcDpsSameDir_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update to v{0} of Blish HUD failed.  Relaunch Blish HUD to try again.  The error was:
        ///
        ///{1}.
        /// </summary>
        internal static string CoreUpdateFailed_Description {
            get {
                return ResourceManager.GetString("CoreUpdateFailed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There are other instances of Blish HUD running.  Please close the other instances first and then run Blish HUD again to complete the update..
        /// </summary>
        internal static string CoreUpdateFailed_Description_Timeout {
            get {
                return ResourceManager.GetString("CoreUpdateFailed_Description_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update Failed!.
        /// </summary>
        internal static string CoreUpdateFailed_Title {
            get {
                return ResourceManager.GetString("CoreUpdateFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à to load your settings.
        /// </summary>
        internal static string FileSaveAccessDenied_Action_ToLoadSettings {
            get {
                return ResourceManager.GetString("FileSaveAccessDenied_Action_ToLoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à to save your settings.
        /// </summary>
        internal static string FileSaveAccessDenied_Action_ToSaveSettings {
            get {
                return ResourceManager.GetString("FileSaveAccessDenied_Action_ToSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à to update Blish HUD.
        /// </summary>
        internal static string FileSaveAccessDenied_Action_ToUpdate {
            get {
                return ResourceManager.GetString("FileSaveAccessDenied_Action_ToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blish HUD was actively blocked saving to &apos;{0}&apos; {1}.
        ///
        ///This is typically due to an anti-virus blocking us or Window&apos;s Controlled Folder Access. Ensure that Blish HUD is explicitly marked as allowed by your anti-virus..
        /// </summary>
        internal static string FileSaveAccessDenied_Description {
            get {
                return ResourceManager.GetString("FileSaveAccessDenied_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blish HUD Was Blocked From Saving Data!.
        /// </summary>
        internal static string FileSaveAccessDenied_Title {
            get {
                return ResourceManager.GetString("FileSaveAccessDenied_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check our &lt;a href=&quot;{0}&quot;&gt;troubleshooting guide&lt;/a&gt; for this issue or join our &lt;a href=&quot;{1}&quot;&gt;Discord 💢help channel&lt;/a&gt;..
        /// </summary>
        internal static string GenericUrl_Footer {
            get {
                return ResourceManager.GetString("GenericUrl_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Something explicitly blocked us from making a web request {0}.
        ///
        ///If you have an anti-virus or third party firewall utility, please ensure that Blish HUD is manually excluded in its filters..
        /// </summary>
        internal static string HttpAccessDenied_Description {
            get {
                return ResourceManager.GetString("HttpAccessDenied_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Web access blocked!.
        /// </summary>
        internal static string HttpAccessDenied_Title {
            get {
                return ResourceManager.GetString("HttpAccessDenied_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blish HUD was unable to find the ref.dat file. When you download Blish HUD, be sure to extract all files from the zip and ensure they are within the same directory as Blish HUD.exe..
        /// </summary>
        internal static string MissingRef_Description {
            get {
                return ResourceManager.GetString("MissingRef_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blish HUD Needs Re-extracted!.
        /// </summary>
        internal static string MissingRef_Title {
            get {
                return ResourceManager.GetString("MissingRef_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blish HUD was unable to access to Guild Wars 2 process. It was likely started as an administrator.
        ///
        ///Relaunch Blish HUD as an administrator or relaunch Guild Wars 2 without admin..
        /// </summary>
        internal static string Win32AccessDenied_Description {
            get {
                return ResourceManager.GetString("Win32AccessDenied_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blish HUD Access Denied!.
        /// </summary>
        internal static string Win32AccessDenied_Title {
            get {
                return ResourceManager.GetString("Win32AccessDenied_Title", resourceCulture);
            }
        }
    }
}
