name: Release Drafter

on:
  push:
    branches:
      - dev

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5.22.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
